version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: autocare
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_URL: "mysql+pymysql://root:passwd@db:3306/autocare"

volumes:
  mysql_data:
