name: Trigger auto deployment for autocare-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ develop ]
    paths:
    - '**'
    - '.github/workflows/autocare-api-AutoDeployTrigger-315d9dc5-3d52-4b1c-8566-e0710b449a65.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AUTOCAREAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AUTOCAREAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AUTOCAREAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: autocare.azurecr.io
          registryUsername: ${{ secrets.AUTOCAREAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AUTOCAREAPI_REGISTRY_PASSWORD }}
          containerAppName: autocare-api
          resourceGroup: autocare
          imageToBuild: autocare.azurecr.io/autocare-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


